# Generated by Django 3.2.18 on 2023-04-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data_id', models.CharField(max_length=55)),
                ('csv_data_name', models.CharField(max_length=60)),
                ('GOODS_DESCRIPTION', models.CharField(max_length=250)),
                ('COMMODITY_DESC', models.CharField(max_length=200)),
                ('CIFValue', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GOODS_DESCRIPTION',
        ),
    ]
