# Generated by Django 3.2.18 on 2023-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='COMMODITY_DESC',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='GOODS_DESCRIPTION',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='M2_Declaration_Number',
            field=models.TextField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='Test',
            field=models.TextField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='Test2',
            field=models.TextField(max_length=2550),
        ),
    ]
