# Generated by Django 3.2.18 on 2023-05-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230509_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='Stat_Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
