# Generated by Django 3.2.18 on 2023-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_csvdata_stat_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='Unexpected',
            field=models.TextField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='csvdata',
            unique_together={('Index', 'M2_Declaration_Number', 'CIF_Value', 'Stat_Quantity', 'COMMODITY_DESC', 'GOODS_DESCRIPTION', 'unit_price')},
        ),
    ]
