# Generated by Django 3.2.18 on 2023-05-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230511_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='Unexpected',
            new_name='Result',
        ),
        migrations.AlterUniqueTogether(
            name='csvdata',
            unique_together=set(),
        ),
    ]
